example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_html 
from mywatchlist.views import show_json
from mywatchlist.views import show_json_by_id
from mywatchlist.views import show_xml
from mywatchlist.views import show_xml_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path("html/", show_html, name="show_html"),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include


# TODO: Implement Routings Here

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('todolist/', include('todolist.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = "todolist"

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('login/', login_user, name='login'),
    path('register/', register, name="register"),
    path('create-task/', create_task, name="create_task"),
    path('logout/', logout_user, name="logout"),
    path('update/<int:id>', update_task, name="update_task"),
    path('delete/<int:id>', delete_task, name='delete_task'),
    path('json/', get_todolist_json, name='get_todolist_json'),
    path('add/', add_todolist_item, name='add_todolist_item')
]

example_app/models.py
from django.db import models

# Create your models here.

mywatchlist/models.py
from django.db import models

# Create your models here.

class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=120)
    rating = models.FloatField()
    release_date = models.CharField(max_length=120)
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.TextField(max_length=100)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class TaskForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

mywatchlist/views.py
from django.shortcuts import render

# Create your views here.
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.

data = MyWatchList.objects.all()

watched = MyWatchList.objects.filter(watched=True).count()
not_watched = MyWatchList.objects.filter(watched=False).count()
message = ''
if (watched > not_watched):
    message = "Selamat, kamu sudah banyak menonton!"
else:
    message = "Wah, kamu masih sedikit menonton!"
    
context = {
    "data_watchlist": data,
    "nama": "Muhammad Adryan Haska Putra",
    "npm": "2106750641",
    "message": message
}

def show_mywatchlist(request):
    return render(request, "root.html", context)

def show_html(request):
    return render(request, "mywatchlist.html", context)

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_json_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_xml_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from todolist.forms import TaskForm
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.http.response import JsonResponse

# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    user_logged_in = request.user
    task = Task.objects.filter(user=user_logged_in)
    context = {
        'len_todolist': len(task),
        'todolist': task,
        'user': user_logged_in,
    }
    return render(request, 'todolist.html', context)

def get_todolist_json(request):
    tasks = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', tasks), content_type='application/json')

@login_required(login_url='/todolist/login')
def add_todolist_item(request):
    if request.method == 'POST':
        judul = request.POST.get('title')
        deskripsi = request.POST.get('description')
        new_task = Task(user=request.user, title=judul, description=deskripsi)
        new_task.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)
    
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("todolist:show_todolist")
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)
    
@login_required(login_url='/todolist/login')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            task = Task(title=title, description=description, user=user)
            task.save()
            return redirect('todolist:show_todolist')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = TaskForm()
    return render(request, 'create-task.html', {'form': form})

@login_required(login_url='/todolist/login')
def update_task(request, id):
    task = Task.objects.get(pk=id)
    if task.is_finished:
        task.is_finished = False
    else:
        task.is_finished = True
    task.save()
    return HttpResponseRedirect("/todolist/")

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    user = request.user
    TaskData = Task.objects.filter(user=user).get(pk=id)
    TaskData.delete()
    return JsonResponse({"instance": "Task Dihapus"}, status=200) 

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

mywatchlist/templates/mywatchlist.html
{% block content %}

<h1>Assignment 3 PBP/PBD</h1>

<h5>Name:</h5>
<p>{{nama}}</p>

<h5>Student ID:</h5>
<p>{{npm}}</p>

<table border="2">
  <tr>
    <th>watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release Date</th>
    <th>Review</th>
  </tr>
  {% for mywatchlist in data_watchlist %}
  <tr>
    <th>{{mywatchlist.watched}}</th>
    <th>{{mywatchlist.title}}</th>
    <th>{{mywatchlist.rating}}</th>
    <th>{{mywatchlist.release_date}}</th>
    <th>{{mywatchlist.review}}</th>
  </tr>
  {% endfor %}
</table>

<h1>{{message}}</h1>

{% endblock content %}

mywatchlist/templates/root.html
{% block content %}
<h1>{{message}}</h1>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create-task.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div
  class="login center d-flex flex-column justify-content-center align-items-center"
>
  <h1>Create New Task</h1>
  <br>
  <form
    method="POST"
    action=""
    class="d-flex flex-column justify-content-center"
  >
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputTitle" class="form-label"
        >{{ form.title.label }}:</label
      >
      <input
        class="form-control n-input"
        type="title"
        name="title"
        placeholder="Title"
        style="width: 350px"
      />
    </div>
    <div class="mb-3">
      <label for="exampleInputDescription" class="form-label"
        >{{ form.description.label }}:</label
      >
      <input
        class="form-control n-input"
        type="description"
        name="description"
        placeholder="Description"
        style="width: 350px"
      />
    </div>
    <div>
      <input type="submit" value="Tambahkan Task" class="btn btn-dark n-input" />
    </div>
  </form>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div
  class="login center d-flex flex-column justify-content-center align-items-center"
  style="padding: 20px"
>
  <h1>Login</h1>
    <br>
  <form
    method="POST"
    action=""
    class="d-flex flex-column justify-content-center "
  >
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputUsername" class="form-label">Username</label>
      <input
        type="text"
        name="username"
        placeholder="Username"
        class="form-control"
        style="width: 350px"
      />
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input
        type="password"
        class="form-control"
        name="password"
        placeholder="Password"
        style="width: 350px"
      />
    </div>
    <button type="submit" class="btn login_btn btn-dark" value="login">
      Login
    </button>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} 
  <div class="n-text">Belum mempunyai akun ? <a href="{% url 'todolist:register' %}" class="link">Buat Akun</a></div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %} {% block content %}

<div class="login center d-flex flex-column justify-content-center align-items-center" style="padding:20px;">
  <h1>Formulir Registrasi</h1>
  <br>
  <form
    method="POST"
    action=""
    class="d-flex flex-column justify-content-center"
  >
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputUsername" class="form-label"
        >{{ form.username.label }}</label
      >
      <div class="form-help">{{form.username.help_text}}</div>
      <input class="form-control" type="username" name="username" placeholder="Username">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label"
        >{{ form.password1.label }}</label
      >
      <div class="form-help">{{form.password1.help_text}}</div>
      <input class="form-control" type="password" name="password1" placeholder="Password">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword2" class="form-label"
        >{{ form.password2.label }}</label
      >
      <div class="form-help">{{form.password2.help_text}}</div>
      <input class="form-control" type="password" name="password2" placeholder="Confirm Password">
    </div>
    <button type="submit" class="btn login_btn btn-dark" value="login">
      Daftar
    </button>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} 
  <div class="n-text">Sudah mempunyai akun ?<a href="{% url 'todolist:login' %}" class="link"> Masuk</a></div>
  
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<script>
  function show(data) {
    let content = "";
    for (let i = 0; i < data.length; i++) {
      let message = data[i].fields.is_finished ? "Selesai" : "Belum Selesai";
      let button = data[i].fields.is_finished ? "✅" : "⬜";
      let color = data[i].fields.is_finished ? "green" : "red";
      content += `
              <br />
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">${data[i].fields.title}</h5>
                  <p class="card-text">${data[i].fields.description}</p>
                  <div class="columns">
                    <div class="column" style="padding-top: 5px">
                      <p class="date">date ${data[i].fields.date}</p>
                    </div>
                    <div class="column status">
                      <p style="color: ${color}">
                        ${message}
                        <button class="btn">
                          <a href="update/${data[i].pk}" style="text-decoration: none">${button}</a>
                        </button>
                      </p>
                    </div>

                    <div class="column" style="padding-left: 5%">
                      <button class="btn btn-outline-danger" onClick={deleteData(${data[i].pk})}>
                        Hapus
                      </button>
                    </div>
                  </div>
                </div>
              </div>
        `;
      $(".content").html(content);
    }
  }

  // GET
  $(document).ready(function () {
    $(".modal").hide();
    $(".backdrop").hide();
    $.get("/todolist/json/", function (data, status) {
      show(data);
    });
  });

  // Add button
  $(document).ready(function () {
    $(".add-task").click(function () {
      $(".modal").toggle();
      $(".backdrop").toggle();
    });
  });

  // click button
  $(document).ready(function () {
    $(".add-task-button").click(function () {
      let judul = $(".title-c").val();
      let deskripsi = $(".description").val();
      let CSRFtoken = $('input[name="csrfmiddlewaretoken"]').val();
      $.post(
        "/todolist/add/",
        {
          title: judul,
          description: deskripsi,
          csrfmiddlewaretoken: CSRFtoken,
        },
        function () {
          $(".modal").hide();
          $(".backdrop").hide();
          $.get("/todolist/json/", function (data, status) {
            show(data);
          });
        }
      );
    });
  });

  // modal backdrop
  $(document).ready(function () {
    $(".backdrop").click(function () {
      $(".modal").hide();
      $(".backdrop").hide();
    });
  });


  // Delete
  function deleteData(id) {
    $.ajax({
      type: "POST",
      url: `delete/${id}`,
      data: { csrfmiddlewaretoken: "{{ csrf_token }}" },
      dataType: "json",
      success: function () {
        $.get("/todolist/json/", function (data, status) {
            show(data);
          });
      },
    });
  }
</script>

{% endblock meta %} {% block content %}

<nav class="navbar bg-light title">
  <form class="container-fluid form-inline">
    <a class="navbar-brand">{{user}}</a>
    <button class="btn btn-danger" type="button">
      <a href="{% url 'todolist:logout' %}" class="link">Logout</a>
    </button>
  </form>
  <br />
</nav>

<div class="d-flex flex-column justify-content-center align-items-center">
  <br /><br />
  <h1 class="login">{{user}}'s To Do List</h1>
  <br />
  <div class="content" style="width: 50%"></div>
  <br /><br />
  <button class="add-task btn btn-dark" type="button" style="width: 30%">
    Tambah Task Baru
  </button>

  <div class="backdrop"></div>
  <br /><br /><br /><br />

  <div
    class="modal"
    style="
      background: rgb(2, 0, 36);
      background: linear-gradient(
        90deg,
        rgba(2, 0, 36, 1) 0%,
        rgba(106, 17, 203, 0.836594012605042) 100%,
        rgba(0, 212, 255, 1) 100%
      );
    "
  >
    <div
      class="center d-flex flex-column justify-content-center align-items-center"
    >
      {% csrf_token %}
      <h1 class="text-2xl font-bold mb-4" style="color: white">ADD NEW TASK</h1>
      <div class="mb-3">
        <label for="exampleInputTitle" class="judul" style="color: white"
          >Title:</label
        >
        <input
          class="title-c form-control n-input"
          type="title-c"
          name="title-c"
          placeholder="Title"
          style="width: 350px"
          autocomplete="off"
        />
      </div>
      <div class="mb-3">
        <label
          for="exampleInputDescription"
          class="deskripsi"
          style="color: white"
          >Description:</label
        >
        <input
          class="description form-control n-input"
          type="description"
          name="description"
          placeholder="Description"
          style="width: 350px"
          autocomplete="off"
        />
      </div>
      <div>
        <input
          type="submit"
          value="Tambahkan Task"
          class="add-task-button btn btn-dark n-input"
        />
      </div>
    </div>
  </div>
</div>
{% endblock content %}